spring:
  application:
    name: wvp
  profiles:
    active: local272
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.17.20.12:2881/wvp2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: root
          password: yuyue123
          hikari:
            connection-timeout: 20000             # 是客户端等待连接池连接的最大毫秒数
            maximum-pool-size: 200                # 连接池最大连接数
            minimum-idle: 10                       # 连接池最小空闲连接数
            idle-timeout: 300000                  # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
            max-lifetime: 1200000                 # 是池中连接关闭后的最长生命周期（以毫秒为单位)